version: '3.8'

volumes:
  db-data:


services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DEBUG: 'true'
    
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=postgres"

    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    tty: true
    stdin_open: true

  redis:
    image: redis:6-alpine
    ports:
        - "6379:6379"
    tty: true
    stdin_open: true
  celery:
    restart: always
    build:
      context: .
    # command: celery -A app worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web


version: '3.8'

# volumes:
#   db-data:
#   mysqldb_data:


# services:
#   web:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     restart: always
#     volumes:
#       - ./:/usr/src/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - db
#       - redis
#       - mysqldb
#     environment:
#       DEBUG: 'true'
    
#   db:
#     image: postgres:13-alpine
#     restart: always
#     environment:
#       - "POSTGRES_PASSWORD=postgres"

#     ports:
#       - "5432:5432"

#     volumes:
#       - db-data:/var/lib/postgresql/data

#     tty: true
#     stdin_open: true

#   redis:
#     image: redis:6-alpine
#     ports:
#         - "6379:6379"
#     tty: true
#     stdin_open: true

    
#   mysqldb:
#     image: mysql:8.0
#     environment:
#       - MYSQL_ROOT_PASSWORD=mysql
#       - MYSQL_DATABASE=mysql
#       - MYSQL_USER=mysql
#       - MYSQL_PASSWORD=mysql
#     volumes:
#       - mysqldb_data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     expose:
#       - "3306"

#   celery:
#     restart: always
#     build:
#       context: .
#     command: ['celery', '-A', 'app', 'worker', '-l', 'info']
#     volumes:
#       - ./app:/app
#     env_file:
#       - ./.env
#     depends_on:
#       - db
#       - redis
#       - web
#       - mysqldb